### PR TITLE
Feature/iii 3566 status button

### PR DESCRIPTION
**Pull request by simon-debruijn**
### Added
- button to redirect to event status page (that will live in react)

### Changed
- updated fontawesome to use newer icons

These changes have to go with it: https://github.com/cultuurnet/udb3-angular-app/pull/161

---
Ticket: https://jira.uitdatabank.be/browse/III-3566

### CODE REVIEW

**Comment by bertramakers** [comment]
Shouldn't we put this behind a feature toggle (can be as simple as a config parameter), or hold off on merging this until the status page is actually ready? Otherwise this will block any other deployments of the Angular app for bug fixes etc because then this button will show up in production.

**Comment by simon-debruijn** [comment]
> Shouldn't we put this behind a feature toggle (can be as simple as a config parameter), or hold off on merging this until the status page is actually ready? Otherwise this will block any other deployments of the Angular app for bug fixes etc because then this button will show up in production.

Good idea just leve this PR open until react is implemented

**Comment by bertramakers** [comment]
Yeah aside from that this looks good. Maybe we should make this a draft PR so it doesn't get merged accidentally?

**Review by bertramakers — APPROVED** [review]

**Comment by simon-debruijn** [comment]
Converted to draft. There are also other changes being made in this PR aswell as on [udb3-angular-app](https://github.com/cultuurnet/udb3-angular-app) that are required with this upgrade of fontawesome.

**Comment by bertramakers** [comment]
@simon-debruijn don't forget to look into the failing tests btw. It seems like the change in icons caused some to break.

**Pull request closed without merging**
