### PR TITLE
Bug/her 276 fix step 2

### PR DESCRIPTION
**Pull request by simon-debruijn**
### Fixed
- step 2 unwanted disabled state

---
Ticket: https://jira.uitdatabank.be/browse/HER-276

Screenshot:

Schermafbeelding 2021-03-09 om 11 16 30
 The svg's won't be missing on test

### CODE REVIEW

**Comment by bertramakers** [comment]
Isn't this also a bug on udb3 that we should deploy asap then?

Also the tests are failing.

**Comment by LucWollants** [comment]
> Isn't this also a bug on udb3 that we should deploy asap then?

I think this is only failing on OMD because OMD creates a default "preselected" date. That preselected data is a timespan object with missing status. A missing status results in this bad UI state.

**Comment by simon-debruijn** [comment]
> > Isn't this also a bug on udb3 that we should deploy asap then?
> 
> I think this is only failing on OMD because OMD creates a default "preselected" date. That preselected data has a timespan object with missing status. A missing status results in this bad UI state.

Indeed, I think this doesn't happen because of the following code:

```javascript
var calendarConfig = _.get(appConfig, 'calendarHighlight');

if (EventFormData.isEvent && calendarConfig && calendarConfig.date) {
  preselectDate(calendarConfig);
}
```

`calendarHighlight` exists on both, but `calendarHighlight.date` is `""` on udb3-angular itself.

**Review by LucWollants — APPROVED** [review]

**Comment by bertramakers** [comment]
Aha I see! Thanks for clarifying :)

**Pull request merged**
