### PR TITLE
III-3104 On the event preview I added a href attribute to the organizer

### PR DESCRIPTION
**Pull request by simonpubliq**
### Added
On the event preview I added a href attribute to the organizer

---
Ticket: https://jira.uitdatabank.be/browse/III-3104

### CODE REVIEW

**Comment by simonpubliq** [comment]
Behaviour after:
Schermafbeelding 2020-06-19 om 09 53 20
Schermafbeelding 2020-06-19 om 09 53 34

**Comment by bertramakers** [comment]
Hey @simonpubliq, thanks for the change. Can you remove the `.DS_Store` file and add it to your global `.gitignore` please? https://gist.github.com/subfuzion/db7f57fff2fb6998a16c

Also make sure to check what you're staging before you commit, don't just stage everything and commit without verifying. That can prevent mistakes like these 😉

**Comment by simonpubliq** [comment]
> Hey @simonpubliq, thanks for the change. Can you remove the `.DS_Store` file and add it to your global `.gitignore` please? https://gist.github.com/subfuzion/db7f57fff2fb6998a16c
> 
> Also make sure to check what you're staging before you commit, don't just stage everything and commit without verifying. That can prevent mistakes like these 😉

Thanks for the feedback, it should be fixed now.

**Comment by bertramakers** [comment]
Yep it's fixed now, but also try to avoid altering the history and force pushing.

For example: https://help.github.com/en/github/using-git/about-git-rebase

> Warning: Because changing your commit history can make things difficult for everyone else using the repository, it's considered bad practice to rebase commits when you've already pushed to a repository. To learn how to safely rebase on GitHub, see "About pull request merges."

It's not an issue in this case I think, unless someone had the same commit checked out locally but I don't think that was the case now.

**Comment by bertramakers** [comment]
The change itself looks good though 👍

**Comment by simonpubliq** [comment]
@brampauwelyn the files in dist directory are also added after grunt build

**Pull request merged**
