### PR TITLE
III-3065 - fix issue, change organizer to organizers

### PR DESCRIPTION
**Pull request by brampauwelyn**
### Added
- code to load all organizers at once (with `embed: true` param) instead of doing seperate requests for each id. 

### Changed
- moved the `reformatJsonLDData` to seperate function to increase reusability. 

### Fixed
- in formatJsonLDEntity switch case change `organizer` to `organizers`
---
Ticket: [https://jira.uitdatabank.be/browse/III-3065](https://jira.uitdatabank.be/browse/III-3065)

### CODE REVIEW

**Comment by bertramakers** [comment]
You also made the exact same change in an unrelated PR? https://github.com/cultuurnet/udb3-angular/pull/546/commits/fbe161834574a6c20950d601d6e0c3a50c9c36e3

**Comment by brampauwelyn** [comment]
> You also made the exact same change in an unrelated PR? [fbe1618](https://github.com/cultuurnet/udb3-angular/commit/fbe161834574a6c20950d601d6e0c3a50c9c36e3)



> I tested this locally and the organizers did show up for me. Why would this be broken on some environments and not others? 🤔
> 
> Edit:
> If I check https://io-test.uitdatabank.be/organizers/?apiKey=0a76cd2a-7066-11e7-a783-0271c1cbe993 I see `@type: "Organizer"`, and when I add `embed=true` I see `@context: "/contexts/organizer"`. Neither is plural?
> 
> Edit 2:
> Looking at the exact URL linked in the related ticket, [https://udb-silex-acc.uitdatabank.be/organizers/?creator=86a02c65-696d-4c16-a9b1-9e3bc8e6303c&limit=50&sort[modified]=desc&start=0&apiKey=deb306a6-6f46-4c98-89ce-b03ec4fd11e2](https://udb-silex-acc.uitdatabank.be/organizers/?creator=86a02c65-696d-4c16-a9b1-9e3bc8e6303c&limit=50&sort%5Bmodified%5D=desc&start=0&apiKey=deb306a6-6f46-4c98-89ce-b03ec4fd11e2) (I added an API key), you also see singular "Organizer".

@bertramakers 
Because in the code he uses the the "@id"  property and this returns "organizers".
[See line](https://github.com/cultuurnet/udb3-angular/blob/db88e53e4703c115bb2eeaac1d249dd23258ef17/src/core/udb-api.service.js#L206)

**Comment by brampauwelyn** [comment]
> You also made the exact same change in an unrelated PR? [fbe1618](https://github.com/cultuurnet/udb3-angular/commit/fbe161834574a6c20950d601d6e0c3a50c9c36e3)

I've accidentally committed it on another feature branch as well...

**Comment by bertramakers** [comment]
> > You also made the exact same change in an unrelated PR? [fbe1618](https://github.com/cultuurnet/udb3-angular/commit/fbe161834574a6c20950d601d6e0c3a50c9c36e3)
> 
> I've accidentally committed it on another feature branch as well...

So it's already merged no? Still I don't get why it should be plural.

**Comment by brampauwelyn** [comment]
> > Because in the code he uses the the "@id" property and this returns "organizers".
> 
> I'm not sure if that's reliable because in the long run we should also make it plural in the @id property of events and places, since the paths should always be plural. They're just singular sometimes because they weren't consistent in the past.

I agree however this was considered a quick fix.
It would be better to use the `@type` property.

**Comment by bertramakers** [comment]
> > > Because in the code he uses the the "@id" property and this returns "organizers".
> > 
> > 
> > I'm not sure if that's reliable because in the long run we should also make it plural in the @id property of events and places, since the paths should always be plural. They're just singular sometimes because they weren't consistent in the past.
> 
> I agree however this was considered a quick fix.
> It would be better to use the `@type` property.

Alright that seems fair, let's merge this and pick this up again once we can make the `@type` property consistent on the back-end.

**Comment by bertramakers** [comment]
Nice work @brampauwelyn! Is it safe to delete the branch?

**Comment by brampauwelyn** [comment]
> Nice work @brampauwelyn! Is it safe to delete the branch?

Jup sorry, forgot to delete it after merging.

**Pull request merged**
